### ISSUE TITLE
prevent proxy server as dns resolver

### ISSUE THREAD

**Issue by fsheidaiee** [a86913179/clash-tun#1]
Hi
with tun mode
when testing dns leak, I see my proxy server address as a dns resolver.
is there anyway to prevent this?
for example when setting dns nameserver to cloudflare, I only want to see cloudflare's servers as dns resolver.
thanks

**Comment by a86913179** [comment]
How did you test it? I suggest you using this site (https://browserleaks.com/dns) for testing.
For clash, any rule matches proxy policy will be resolved by remote server. The dns nameservers in `config.yaml` are just used for matching rules.
In your case, I guess you have set up a dns server on your server.
You should edit `/etc/resolv.conf` or proxy server side configuration to change dns nameservers.

**Comment by fsheidaiee** [comment]
> How did you test it? I suggest you using this site (https://browserleaks.com/dns) for testing.
> For clash, any rule matches proxy policy will be resolved by remote server. The dns nameservers in `config.yaml` are just used for matching rules.
> In your case, I guess you have set up a dns server on your server.
> You should edit `/etc/resolv.conf` or proxy server side configuration to change dns nameservers.

No difference, even if I set nameserver to 'https://dns.adguard.com/dns-query' i see my proxy server address beside adguard as adns resolver in browserleaks site.

**Comment by fsheidaiee** [comment]
When I use proxifier over socks 5 with clash core (no tun mode)
I don't see my proxy server address as a dns resolver.
when using tun/tap mode is see the proxy server address as dns resolver beside the dns provider.
