### ISSUE TITLE
你好，vbs添加启动无法启动tun有方法吗

### ISSUE THREAD

**Issue by yiiyahui** [a86913179/clash-tun#3]
如题，如果用winsw加载到服务的话，tun正常
用vbs添加自启动的话，clash正常,但无tun
谢谢

**Comment by a86913179** [comment]
把start.bat添加到windows启动目录下即可
如果不想要弹窗可以用组策略添加开机脚本

**Comment by yiiyahui** [comment]
OK.感谢回复！
